### ISSUE TITLE
Wanted to Change the background color and the submit button size

### ISSUE THREAD

**Issue by ratna-jaiswal** [muhtalhakhan/Hacktoberfest2024#47]
![Screenshot 2024-10-16 135543](https://github.com/user-attachments/assets/b8e6ff5e-0f76-4119-8f59-5cbbaa27d89c)

@muhtalhakhan pls assign this issue to me and add hacktoberfest label

**Comment by Daksh-134** [comment]
Hi @ratna-jaiswal ,pls assign this issue to me if it is not completed

**Comment by ratna-jaiswal** [comment]
> Hi @ratna-jaiswal ,pls assign this issue to me if it is not completed

Hi @Daksh-134 I am working on it

**Comment by ratna-jaiswal** [comment]
> Hi @ratna-jaiswal ,pls assign this issue to me if it is not completed

PR #54

**Comment by muhtalhakhan** [comment]
Your PR has already been accepted.
