### ISSUE TITLE
Set Up Basic HTML Form Structure | Forms Portal

### ISSUE THREAD

**Issue by muhtalhakhan** [muhtalhakhan/Hacktoberfest2024#8]
Create an HTML file with a form that includes fields like name, email, and comments.

**Comment by surajb0710** [comment]
@muhtalhakhan Can you please assign this to me?

**Comment by muhtalhakhan** [comment]
> @muhtalhakhan Can you please assign this to me?

Sure!

**Comment by Tanisha800** [comment]
please assign this to me

**Comment by muhtalhakhan** [comment]
> please assign this to me
> 

It's done already.
